language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  #- make test #zastapione przez mate test_xunit
  - make lint
  - make docker_build
  - make docker_push
  - make test_xunit #zamiast make test
deploy:
  provider: heroku
  app: salty-wildwood-30209 #nazwa z heroku
  api_key: ${HEROKU_API_KEY} #zmienna srodowiskowa
